import { useState, useEffect, memo, useRef, useMemo } from 'react';
import { motion } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeSlug from 'rehype-slug';
import rehypeKatex from 'rehype-katex';
import { RefreshCw, BookOpen, User, Clock, ListTree } from 'lucide-react';
import 'katex/dist/katex.min.css';
import CodeBlock from './CodeBlock';

// --- Independent Table of Contents Component ---
// Separated to prevent re-rendering the heavy Markdown content when creating active highlight
const TableOfContents = memo(({ headings }) => {
  const [activeId, setActiveId] = useState(null);

  useEffect(() => {
    if (headings.length === 0) return;
    
    // Set initial active state
    setActiveId(headings[0]?.id);

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting && entry.target.id) {
            setActiveId(entry.target.id);
          }
        });
      },
      {
        root: null,
        // Adjust rootMargin to trigger earlier/smoother
        // -80% bottom means we trigger when the header is in the top 20% of screen
        rootMargin: '0px 0px -80% 0px', 
        threshold: 0
      }
    );

    headings.forEach(h => {
      const el = document.getElementById(h.id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, [headings]);

  const scrollToHeading = (id) => {
    const element = document.getElementById(id);
    if (element) {
      setActiveId(id);
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  if (headings.length === 0) return null;

  return (
    <div className="hidden 2xl:block w-64 flex-shrink-0 h-screen sticky top-0 py-12 pr-2 overflow-y-auto custom-scrollbar">
      {/* Track Line Container */}
      <div className="relative pl-6 border-l border-slate-200 dark:border-slate-800">
        <h4 className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-6 flex items-center gap-2">
          <ListTree size={12} />
          Contents
        </h4>
        <ul className="space-y-0.5 relative">
          {headings.map((h, i) => {
            const isActive = activeId === h.id;
            
            // Dynamic Typography based on level
            let textClass = "text-slate-500 dark:text-slate-500 font-normal";
            if (h.level === 1) textClass = "font-bold text-slate-800 dark:text-slate-100 mb-1 mt-3 first:mt-0";
            else if (h.level === 2) textClass = "font-medium text-slate-700 dark:text-slate-300 mt-1";
            else textClass = "text-slate-500 dark:text-slate-400";

            if (isActive) {
               // Active Override
               textClass = "text-indigo-600 dark:text-indigo-400 font-semibold";
               if (h.level === 1) textClass += " font-bold"; 
            }

            return (
              <li key={i} className="relative group">
                {/* Active Indicator Pille - Animated Sliding Marker */}
                {isActive && (
                  <motion.div
                    layoutId="toc-marker"
                    className="absolute -left-[25px] top-1.5 bottom-1.5 w-[3px] rounded-full bg-indigo-600 dark:bg-indigo-400"
                    transition={{ type: "spring", stiffness: 300, damping: 25 }}
                  />
                )}
                
                <button 
                  onClick={() => scrollToHeading(h.id)}
                  className={`text-left w-full transition-colors duration-200 py-1 text-xs leading-relaxed block
                    hover:text-indigo-500 dark:hover:text-indigo-300
                    ${textClass}
                  `}
                  style={{ 
                    // Subtle indentation
                    paddingLeft: h.level === 1 ? '0px' : `${(h.level - 1) * 12}px` 
                  }}
                >
                  {h.text}
                </button>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
});

// --- Docs View ---
const DocsView = memo(({ selectedFile, content, loading }) => {
  const [headings, setHeadings] = useState([]);
  const contentRef = useRef(null);

  useEffect(() => {
    // Extract headings from rendered DOM to get actual IDs generated by rehypeSlug
    if (contentRef.current && content) {
      const headingElements = contentRef.current.querySelectorAll('h1, h2, h3');
      const extractedHeadings = Array.from(headingElements).map(el => ({
        level: parseInt(el.tagName.substring(1)),
        text: el.textContent,
        id: el.id
      }));
      setHeadings(extractedHeadings);
    }
  }, [content]);

  // Image URL Transformer
  const transformImageUri = (uri) => {
    if (uri.startsWith('http') || uri.startsWith('/')) {
      return uri;
    }
    // Construct path relative to the current document
    // selectedFile.path is like "folder/doc.md"
    // Backend serves files at /raw/folder/image.png
    const docDir = selectedFile?.path.split('/').slice(0, -1).join('/');
    const finalUrl = docDir ? `/raw/${docDir}/${uri}` : `/raw/${uri}`;
    return finalUrl;
  };

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="min-h-full flex flex-col"
    >
      <div className="flex-1 flex">
        {/* Content Area */}
        <div className="flex-1 p-4 md:p-8 lg:p-16 relative min-w-0">
          {loading ? (
            <div className="absolute inset-0 flex items-center justify-center text-slate-400 dark:text-slate-500 gap-2 h-96">
              <RefreshCw className="animate-spin" /> Loading...
            </div>
          ) : selectedFile ? (
            <div className="max-w-5xl mx-auto">
              {/* Metadata Header */}
              <div className="mb-10 pb-8 border-b border-slate-200 dark:border-slate-700">
                  <h1 className="text-4xl font-extrabold text-slate-900 dark:text-slate-100 mb-6 tracking-tight">{selectedFile.name.replace(/\.md$/i, '')}</h1>
                  <div className="flex flex-wrap items-center gap-4 text-xs font-medium text-slate-500 dark:text-slate-400">
                    <div className="flex items-center gap-2 bg-white dark:bg-slate-800 px-3 py-1.5 rounded-full border border-slate-200 dark:border-slate-700 shadow-sm">
                        <User size={14} className="text-indigo-500 dark:text-indigo-400"/>
                        <span>Created by <span className="text-slate-700 dark:text-slate-300 font-bold">{selectedFile.owner || 'Unknown'}</span></span>
                    </div>
                    <div className="flex items-center gap-2 bg-white dark:bg-slate-800 px-3 py-1.5 rounded-full border border-slate-200 dark:border-slate-700 shadow-sm">
                        <Clock size={14} className="text-indigo-500 dark:text-indigo-400"/>
                        <span>Updated <span className="text-slate-700 dark:text-slate-300 font-bold">{selectedFile.modTime || 'Unknown'}</span></span>
                    </div>
                  </div>
              </div>

              <article ref={contentRef} className="prose prose-slate prose-lg max-w-none 
                prose-headings:font-sans prose-headings:text-slate-900 dark:prose-headings:text-slate-100 prose-headings:scroll-mt-20
                prose-h1:text-4xl prose-h1:font-black prose-h1:mt-12 prose-h1:mb-6 prose-h1:tracking-tight prose-h1:leading-tight
                prose-h2:text-2xl prose-h2:font-bold prose-h2:mt-12 prose-h2:mb-6 prose-h2:tracking-tight prose-h2:leading-snug
                prose-h3:text-xl prose-h3:font-semibold prose-h3:mt-8 prose-h3:mb-4 prose-h3:leading-snug
                prose-p:text-slate-600 dark:prose-p:text-slate-300 prose-p:leading-relaxed prose-p:mb-4 prose-p:break-words
                prose-strong:font-semibold prose-strong:text-slate-800 dark:prose-strong:text-slate-200
                prose-a:text-indigo-600 dark:prose-a:text-indigo-400 hover:prose-a:text-indigo-500 dark:hover:prose-a:text-indigo-300 prose-a:no-underline hover:prose-a:underline prose-a:break-all
                prose-pre:my-0 prose-pre:p-0 prose-pre:bg-transparent prose-pre:shadow-none prose-pre:border-none prose-pre:overflow-visible
                prose-code:before:content-none prose-code:after:content-none prose-code:text-slate-800 dark:prose-code:text-slate-200 prose-code:bg-slate-100 dark:prose-code:bg-slate-800 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded
                prose-img:rounded-xl prose-img:my-8 prose-img:max-w-full prose-img:mx-auto prose-img:block
                prose-blockquote:border-l-4 prose-blockquote:border-indigo-500 dark:prose-blockquote:border-indigo-600 prose-blockquote:bg-indigo-50 dark:prose-blockquote:bg-indigo-950/30 prose-blockquote:py-2 prose-blockquote:px-6 prose-blockquote:rounded-lg prose-blockquote:not-italic prose-blockquote:text-slate-700 dark:prose-blockquote:text-slate-300 prose-blockquote:my-4
                prose-ul:list-disc prose-ul:pl-6 prose-ul:marker:text-indigo-400 dark:prose-ul:marker:text-indigo-500
                prose-ol:list-decimal prose-ol:pl-6 prose-ol:marker:text-indigo-500 dark:prose-ol:marker:text-indigo-400
                prose-li:mb-2 prose-li:text-slate-600 dark:prose-li:text-slate-300
                prose-table:border-collapse prose-table:w-full
                prose-th:bg-slate-100 dark:prose-th:bg-slate-800 prose-th:text-slate-900 dark:prose-th:text-slate-100 prose-th:p-3 prose-th:border dark:prose-th:border-slate-700
                prose-td:p-3 prose-td:border dark:prose-td:border-slate-700 prose-td:text-slate-700 dark:prose-td:text-slate-300
                prose-hr:border-slate-200 dark:prose-hr:border-slate-700
              ">
                  <ReactMarkdown 
                    remarkPlugins={[remarkGfm, remarkMath]}
                    rehypePlugins={[rehypeSlug, rehypeKatex]}
                    urlTransform={transformImageUri}
                    components={{
                      code: CodeBlock
                    }}
                  >
                    {content}
                  </ReactMarkdown>
              </article>
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-slate-400 dark:text-slate-500 min-h-[60vh]">
                <div className="w-24 h-24 bg-white dark:bg-slate-800 rounded-full flex items-center justify-center mb-8 shadow-sm border border-slate-100 dark:border-slate-700">
                  <BookOpen size={48} className="text-slate-300 dark:text-slate-600" />
                </div>
                <h3 className="text-xl font-bold text-slate-700 dark:text-slate-300 mb-3">No Documentation Available</h3>
                <p className="text-slate-400 dark:text-slate-500 max-w-sm text-center leading-relaxed">Please create Markdown files in the configured docs directory to get started.</p>
            </div>
          )}
        </div>

        {/* Right TOC Sidebar (Now Independent) */}
        {!loading && selectedFile && (
          <TableOfContents headings={headings} />
        )}
      </div>
    </motion.div>
  );
});

export default DocsView;
